### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [RTMaloney/intro-data-capstone-musclehub#5]
(Exceeds Expectations)

Well done on this project! Good job on all the analysis as well as data visualizations. In addition, your presentation slides were very thorough and efficient in presenting your findings. Great attention to details as well, including making notes and comments in your Python script as well as adding the additional error measure in your bar charts!

One thing you could look out for next time are more efficient ways to write your code (#1, #2, #4). You're still getting the correct answers, which is great! But finding simpler ways to achieve the same results could help save you time and make the code more easy to understand for others reading it.

As a further challenge, continue exploring these datasets and see if you could ask some more research questions about it. Try designing your own tests and continue to play around with different ways of data visualizations. Have fun!

**Comment by RTMaloney** [comment]
Thank you cyouh95 !
